name: 'Say "How dare you?" to Dave'. 

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "50 4 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: sayhowdareyoutodave
        env: 
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: curl "https://api.telegram.org/bot$TOKEN/sendDocument?document=CgACAgQAAxkBAAMRYaGFsz_fRQYSjcwxO2N2F4tutUwAAooCAAJv7IVS5gIOmkGeny4iBA&chat_id=$CHAT_ID"
