name: Sayhowdareyoutodave 

on:
  schedule:
    - cron: "22 5 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: well
        env: 
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: curl "https://api.telegram.org/bot$TOKEN/sendDocument?document=CgACAgQAAxkBAAMRYaGFsz_fRQYSjcwxO2N2F4tutUwAAooCAAJv7IVS5gIOmkGeny4iBA&chat_id=$CHAT_ID"
